### ISSUE TITLE
Hashed, searchable columns

### ISSUE THREAD

**Issue by brycedarling** [danielberkompas/cloak_ecto#4]
I cannot find any documentation on how to make make hashed, searchable columns to go along with my encrypted column. Any help would be appreciated, thanks for the sweet lib!

**Comment by brycedarling** [comment]
Nevermind, found it in the docs after thinking to search for "hash" ;)

https://hexdocs.pm/cloak_ecto/Cloak.Ecto.PBKDF2.html#module-usage

Thank you!

**Comment by sveredyuk** [comment]
Hi, I have maybe a stupid question but is it possible to search with like or like by hashed fields?

**Comment by brycedarling** [comment]
@sveredyuk as far as I know, the hash is only useful for an exact equality lookup. a string like `"this is some text"` will be hashed to a value like `DV5hk0ryjAsvSp3uFhhLog1tLp3/aA7/ttGFAq1yg9k=` so it wouldn't be very useful to do a `LIKE` query on. when searching the table, the value you are looking for also gets hashed so that it can try find a row with that exact same matching hash.

**Comment by acrolink** [comment]
> @sveredyuk as far as I know, the hash is only useful for an exact equality lookup. a string like `"this is some text"` will be hashed to a value like `DV5hk0ryjAsvSp3uFhhLog1tLp3/aA7/ttGFAq1yg9k=` so it wouldn't be very useful to do a `LIKE` query on. when searching the table, the value you are looking for also gets hashed so that it can try find a row with that exact same matching hash.

I have the same suspicion. Correct, true ? only exact full string match would work?

**Comment by sveredyuk** [comment]
Definitely. Using `LIKE` for hashed values will give you nothing. Or exact match or just use another soution

**Comment by jaimeiniesta** [comment]
I also came here looking for a way to search with `LIKE` in a hashed column, now I understand this is not possible. Maybe the documentation could say something like "findable" instead of "searchable" to imply that hashes allow you to find matching records, like exact emails or tokens, but not inside the content with `LIKE`.

A possible solution if there are not many records is to load the content in memory so that it's decrypted and then search with Elixir.
